server:
  type: simple
  maxThreads: 1024
  applicationContextPath: /application
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
  requestLog:
    appenders:
      - type: console

admin:
  healthChecks:
    minThreads: 1
    maxThreads: 4
    workQueueSize: 1

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      queueSize: 512
      discardingThreshold: 0
      timeZone: UTC
      target: stdout
      logFormat: "%-5p [%d{ISO8601,UTC}] %c: %m%n%rEx"

baseHttpClient:
  timeout: 5000
  connectionTimeout: 5000
  timeToLive: 1
  cookiesEnabled: false
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 0
  retry: true
  retries: 3
  socketTimeout: 5000

nseDataScrapper:
  baseUrl: "https://www.nseindia.com/"
  latestStockPriceEndPoint: "live_market/dynaContent/live_watch/get_quote/GetQuote.jsp?symbol="
  dataFileBasePath: "/Users/durgesh.soni/projects/stock-trading-estimator/src/main/java/stock/trading/data/"

